export const RECEIVE_ADDRESS='receive-address'
export const RECEIVE_CATEGORYS ='receive-categorys'
export const RECEIVE_SHOPS='receive-shops'
export const RECEIVE_USER='receive-user'
export const RESET_USER='reset-user'
export const RECEIVE_TOKEN='receive-token'
export const RESET_TOKEN='reset-token'